mysql:
  user: 'civ'
  password: '<password>'
  host: localhost
  database: civ
  port: 3306
  poolsize: 10
  connectionTimeout: 10000
  idleTimout: 600000
  maxLifetime: 7200000
  savesPerDay: 64
commonSettings:
  cancelReinforcementModeInBastionField: false
  listBastionTimeout: 2000
bastions:
#The first bastion in this list will be used as the default type
#This only really matters the first time your start it up when converting from old bastion
#All bastions in the db will be flagged as, in this instance, citybastion
  citybastion:
    block:
      material: ENDER_CHEST
      durability: 0
      name: City Bastion 
      lore: 
        - City Bastions will keep exiled players out and prevent reinforcements
    shortName: City
    squarefield: true
    effectRadius: 100
    includeY: true
    startScaleFactor: 100
    finalScaleFactor: 0.2
    warmupTime: 86400000
    erosionPerDay: 0
    regenPerDay: 0
    blocksToErode: 1
    placementCooldown: 2000
    destroyOnRemove: true
    onlyDirectDestroy: false
    pearls:
      block: true
      blockMidair: false
      scaleFactor: 1
      requireMaturity: true
      consumeOnBlock: false
      damageFirstBastion: false
    elytra:
      block: true
      scaleFactor: 1
      requireMaturity: true
      destroyOnBlock: false
      damageOnBlock: true
      explodeOnBlock: true
      explodeOnBlockStrength: 0
  claimbastion:
    block:
      material: ENDER_CHEST
      durability: 0
      name: Claim Bastion
      lore: 
        - Claim Bastions will protect your claims
    squarefield: true
    effectRadius: 300
    includeY: true
    startScaleFactor: 100
    finalScaleFactor: 0.2
    warmupTime: 86400000
    erosionPerDay: 0
    regenPerDay: 0
    blocksToErode: 1
    placementCooldown: 2000
    destroyOnRemove: false
    onlyDirectDestroy: true
    pearls:
      block: true
      blockMidair: false
      scaleFactor: 1
      requireMaturity: true
      consumeOnBlock: false
      damageFirstBastion: false
    elytra:
      block: false
      scaleFactor: 1
      requireMaturity: true
      destroyOnBlock: false
      damageOnBlock: true
      explodeOnBlock: true
      explodeOnBlockStrength: 0
  bastion:
    block:
      material: ENDER_CHEST
      durability: 0
      name: Vault Bastion
      lore: 
        - Vault Bastions prevent block placement
    squarefield: true
    effectRadius: 10
    includeY: true
    startScaleFactor: 100
    finalScaleFactor: 0.2
    warmupTime: 86400000
    erosionPerDay: 0
    regenPerDay: 0
    blocksToErode: 1
    placementCooldown: 2000
    destroyOnRemove: true
    onlyDirectDestroy: false
    pearls:
      block: true
      blockMidair: true
      scaleFactor: 2
      requireMaturity: true
      consumeOnBlock: true
      damageFirstBastion: true
    elytra:
      block: true
      scaleFactor: 1
      requireMaturity: true
      destroyOnBlock: true
      damageOnBlock: false
      explodeOnBlock: true
      explodeOnBlockStrength: 0
